http://localhost:3000/players/


###

POST http://localhost:3000/players/
Content-Type : application/json

{
  "playerName": "Vishal",
  "jerseyNumber": 10,
  "role": "Bowler"
}


###
http://localhost:3000/players/

###
DELETE http://localhost:3000/players/13